### ISSUE TITLE
ValueError: tile cannot extend outside image

### ISSUE THREAD

**Issue by gogobody** [kirkins/PSD-to-HTML#2]
···
ValueError: tile cannot extend outside image
···

**Comment by gogobody** [comment]
```
Processing Layer: 图层-5
Processing Layer: 图层-26
Processing Layer: Iron-Clad
Processing Layer: 图层-16
Processing Layer: 图层-6
Traceback (most recent call last):
  File "psd.py", line 80, in <module>
    site = layerstoimage(psd.layers)
  File "psd.py", line 72, in layerstoimage
    layer_image = layer.as_PIL()
  File "C:\Python27\lib\site-packages\psd_tools\user_api\psd_image.py", line 103, in as_PIL
    return self._psd._layer_as_PIL(self._index)
  File "C:\Python27\lib\site-packages\psd_tools\user_api\psd_image.py", line 288, in _layer_as_PIL
    return pil_support.extract_layer_image(self.decoded_data, index)
  File "C:\Python27\lib\site-packages\psd_tools\user_api\pil_support.py", line 45, in extract_layer_image
    icc_profile = get_icc_profile(decoded_data)
  File "C:\Python27\lib\site-packages\psd_tools\user_api\pil_support.py", line 114, in _channel_data_to_PIL
    depth=depth
  File "C:\Python27\lib\site-packages\psd_tools\user_api\pil_support.py", line 167, in _get_band_images
    im = _from_8bit_raw(channel.data, size)
  File "C:\Python27\lib\site-packages\psd_tools\user_api\pil_support.py", line 193, in _from_8bit_raw
    return frombytes('L', size, data, "raw", 'L')
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 2100, in frombytes
    im.frombytes(data, decoder_name, args)
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 738, in frombytes
    d.setimage(self.im)
ValueError: tile cannot extend outside image
```

**Comment by spy14414** [comment]
Hi，I met the same problem with you. Did you solve it?
我发现你是中国人，还是说中文吧。请问你对photoshop熟吗？大佬求救QAQ

**Comment by gogobody** [comment]
> Hi，I met the same problem with you. Did you solve it?
> 我发现你是中国人，还是说中文吧。请问你对photoshop熟吗？大佬求救QAQ

复杂图层确实不能处理，这个真没办法，自己老老实实写吧
